#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ${SCR_PATH}compile_it
FNAME="Global"; . ${SCR_PATH}compile_it
FNAME="Utilities"; . ${SCR_PATH}compile_it
FNAME="FileIO_Utilities"; . ${SCR_PATH}compile_it
FNAME="Interpolation"; . ${SCR_PATH}compile_it
FNAME="Legendre_Utilities"; . ${SCR_PATH}compile_it
FNAME="Sorting"; . ${SCR_PATH}compile_it
FNAME="PRNGs"; . ${SCR_PATH}compile_it
FNAME="Statistics"; . ${SCR_PATH}compile_it
FNAME="Root_Solvers"; . ${SCR_PATH}compile_it
FNAME="Gauss_Legendre_w_a"; . ${SCR_PATH}compile_it
FNAME="Quadratures"; . ${SCR_PATH}compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ${SCR_PATH}compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/common/atmo/"
FNAME="USSA76"; . ${SCR_PATH}compile_it
FNAME="IsoTherm"; . ${SCR_PATH}compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
FNAME="Particle_Piles"; . ${SCR_PATH}compile_it
FNAME="cs_Utilities"; . ${SCR_PATH}compile_it
FNAME="Neutron_Utilities"; . ${SCR_PATH}compile_it
FNAME="n_Cross_Sections"; . ${SCR_PATH}compile_it
FNAME="Random_Numbers"; . ${SCR_PATH}compile_it
FNAME="Random_Directions"; . ${SCR_PATH}compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Setups"; . ${SCR_PATH}compile_it
FNAME="Atmospheres"; . ${SCR_PATH}compile_it
FNAME="Satellite_Motion"; . ${SCR_PATH}compile_it
FNAME="Diverge_approx"; . ${SCR_PATH}compile_it
FNAME="Diverge_exact"; . ${SCR_PATH}compile_it
FNAME="Find_Trajectory"; . ${SCR_PATH}compile_it
FNAME="Pathlengths"; . ${SCR_PATH}compile_it
FNAME="Target_Motion"; . ${SCR_PATH}compile_it
FNAME="Tallies"; . ${SCR_PATH}compile_it
FNAME="Detectors"; . ${SCR_PATH}compile_it
FNAME="Neutron_Scatter"; . ${SCR_PATH}compile_it
FNAME="Sources"; . ${SCR_PATH}compile_it
FNAME="MC_Neutron"; . ${SCR_PATH}compile_it
FNAME="Results"; . ${SCR_PATH}compile_it

# MAIN PROGRAM
SRC_PATH="../source/"
FNAME="HASTE_DRIVER"; . ${SCR_PATH}compile_it
