#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ${SCR_PATH}compile_it
FNAME="Global"; . ${SCR_PATH}compile_it
FNAME="Utilities"; . ${SCR_PATH}compile_it
FNAME="Interpolation"; . ${SCR_PATH}compile_it
FNAME="Gauss_Legendre_w_a"; . ${SCR_PATH}compile_it
FNAME="Quadratures"; . ${SCR_PATH}compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/common/atmo/"
FNAME="USSA76"; . ${SCR_PATH}compile_it

#TEST PROGRAM
SRC_PATH="../testing/EPLquads/"
FNAME="EPLquadpoints"
echo "Compiling and linking EPLquadpoints..."
$COMP_NAME $FORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
${RUN_CMD}${FNAME}${EXT}
