#!/bin/sh

#COMPILE
. ./compile_n_Cross_Sections

#TEST PROGRAM
SRC_PATH="../testing/n_CS/"
FNAME="testCS"
echo "Compiling and linking testCS..."
$COMP_NAME $FORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES
echo "Copying resource files..."
rm -fr ${SRC_PATH}Resources
cp -r ../source/resources ${SRC_PATH}Resources

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
${RUN_CMD}${FNAME}${EXT}
