#!/bin/sh
SCR_PATH="../source/common/scripts/"
# CLEAN OLD BUILD FILES
${SCR_PATH}clean

# SET COMPILER FLAGS
. ${SCR_PATH}set_flags
. ${SCR_PATH}echo_flags

# COMMON MODULES
SRC_PATH="../source/common/"
FNAME="Kinds"; . ${SCR_PATH}compile_it
FNAME="Global"; . ${SCR_PATH}compile_it
FNAME="Utilities"; . ${SCR_PATH}compile_it
FNAME="FileIO_Utilities"; . ${SCR_PATH}compile_it
FNAME="Interpolation"; . ${SCR_PATH}compile_it
FNAME="Legendre_Utilities"; . ${SCR_PATH}compile_it
FNAME="Sorting"; . ${SCR_PATH}compile_it
FNAME="PRNGs"; . ${SCR_PATH}compile_it
FNAME="Statistics"; . ${SCR_PATH}compile_it

# ATMOSPHERE MODULES
SRC_PATH="../source/common/atmo/"
FNAME="USSA76"; . ${SCR_PATH}compile_it

# ASTRO MODULES
SRC_PATH="../source/astro/"
FNAME="Astro_Utilities"; . ${SCR_PATH}compile_it

# PARTICLE UTILITIES MODULES
SRC_PATH="../source/parts/"
FNAME="cs_Utilities"; . ${SCR_PATH}compile_it
FNAME="Neutron_Utilities"; . ${SCR_PATH}compile_it
FNAME="n_Cross_Sections"; . ${SCR_PATH}compile_it
FNAME="Random_Numbers"; . ${SCR_PATH}compile_it
FNAME="Random_Directions"; . ${SCR_PATH}compile_it

# MAIN CODE MODULES
SRC_PATH="../source/"
FNAME="Atmospheres"; . ${SCR_PATH}compile_it
FNAME="Target_Motion"; . ${SCR_PATH}compile_it
FNAME="Neutron_Scatter"; . ${SCR_PATH}compile_it
FNAME="Satellite_Motion"; . ${SCR_PATH}compile_it
FNAME="Find_Trajectory"; . ${SCR_PATH}compile_it
FNAME="Diverge_approx"; . ${SCR_PATH}compile_it

#TEST PROGRAM
SRC_PATH="../testing/prevTrajectory/"
FNAME="LPadjoint"
echo "Compiling and linking LPadjoint..."
$COMP_NAME $FORT_FLAGS -o ${SRC_PATH}${FNAME}${EXT} ${SRC_PATH}${FNAME}.f90 $OBJ_FILES

#RUN THE TEST PROGRAM
echo "Running..."
cd ${SRC_PATH}
${RUN_CMD}${FNAME}${EXT}
